# vi: set ft=ruby sts=2 sw=2 ts=2 :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
#
# see https://www.vagrantup.com/docs/vagrantfile/
Vagrant.configure("2") do |config|
  config.vm.box = "centos/7"

  ## Network settins
  # config.vm.network "public_network"
  config.vm.network "private_network", ip: "192.168.33.10"
  config.vm.network "forwarded_port", guest: 80, host: 8080
  config.vm.network "forwarded_port", guest: 443, host: 8083
  config.vm.hostname = 'dockerhost'

  ## Sharing folder settings
  config.vm.synced_folder "../data", "/vagrant_data", create: true, mount_options: ['dmode=777','fmode=777']

  ## VirtualBox specific settings
  config.vm.provider "virtualbox" do |vb|
    vb.name   = "dockerhost"
    vb.memory = "2048"

    # If you want to add extra-disks automaticaly, followings may be helpful.
    # http://askubuntu.com/questions/317338/how-can-i-increase-disk-size-on-a-vagrant-vm
    # https://www.vagrantup.com/docs/virtualbox/configuration.html
  end

  # Enable provisioning with a shell script. Additional provisioners such as
  # Puppet, Chef, Ansible, Salt, and Docker are also available. Please see the
  # documentation for more information about their specific syntax and use.
  config.vm.provision :shell, path: "bootstrap.sh"
end
